-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.


Where the config is set
- src/ToTen.AppHost/AppHost.cs:6-16 — AddAzurePostgresFlexibleServer("postgres").RunAsContainer(...) with no explicit .WithHostPort()/.WithPassword(), so Aspire auto-generates the admin password and picks a random host port each time the container is (re)created.
- The generated password is persisted in the AppHost project's user secrets (not in git): ~/.microsoft/usersecrets/92823f80-554d-4fd2-9ad2-b361574d1318/secrets.json (that GUID is ToTenAppHost.csproj's UserSecretsId). It stays stable across runs unless you delete the container/volume.
- Database name: "ToTen" (from postgres.AddDatabase("ToTenDB", "ToTen") at AppHost.cs:18 — note the resource is called ToTenDB but the actual database is ToTen).
- Username is fixed at postgres (confirmed from a prior container's env: POSTGRES_USER=postgres).

-- How to get the actual values, safely, yourself
-- 1. Run the app: aspire run (or dotnet run --project src/ToTen.AppHost).
-- 2. Open the Aspire Dashboard link printed in the terminal → click the postgres resource → its Endpoints/connection-string details show the live host port (changes per run/container recreation).
-- 3. Get the password in your own terminal (don't want me printing it): dotnet user-secrets list --project src/ToTen.AppHost — or read it straight off the postgres resource's environment variables panel in the Aspire Dashboard.

-- VS Code Postgres extension connection
-- - Host: localhost
-- - Port: whatever the dashboard shows for the postgres resource (not fixed — pgAdmin is the only piece pinned to a port, 5050)
-- - Username: postgres
-- - Password: from step 3
-- - Database: ToTen
-- - SSL: disable/prefer — it's an unauthenticated local dev container, no TLS cert to trust

-- Easier alternative for just browsing/diagramming: Aspire already spins up pgAdmin pre-wired to this server at http://localhost:5050 (AppHost.cs:12-15) — no credentials to hunt down, and pgAdmin has an ERD tool built in (right-click the database → Generate ER Diagram). Worth trying that first if the VS Code extension is just for convenience rather than a hard requirement.

BEGIN;


CREATE TABLE IF NOT EXISTS public."AuditLogEntries"
(
    "Id" uuid NOT NULL,
    "EventType" text COLLATE pg_catalog."default" NOT NULL,
    "ItemId" uuid,
    "ManifestId" uuid,
    "ActorId" text COLLATE pg_catalog."default",
    "OccurredAt" timestamp with time zone NOT NULL,
    "RecordedAt" timestamp with time zone NOT NULL,
    "Payload" jsonb NOT NULL,
    CONSTRAINT "PK_AuditLogEntries" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Boxes"
(
    "Id" uuid NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "LocationId" uuid NOT NULL,
    "OwnerId" text COLLATE pg_catalog."default" NOT NULL,
    "OrganizationId" uuid,
    "ManifestId" uuid,
    CONSTRAINT "PK_Boxes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Categories"
(
    "Id" uuid NOT NULL,
    "Name" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ChatMessages"
(
    "Id" uuid NOT NULL,
    "ThreadId" uuid NOT NULL,
    "SenderId" text COLLATE pg_catalog."default" NOT NULL,
    "Content" text COLLATE pg_catalog."default" NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ChatThreads"
(
    "Id" uuid NOT NULL,
    "Title" text COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatThreads" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."InventoryItems"
(
    "Id" uuid NOT NULL,
    "Name" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "CategoryId" uuid NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "LastUpdatedBy" text COLLATE pg_catalog."default" NOT NULL,
    "OwnerId" text COLLATE pg_catalog."default" NOT NULL,
    "OrganizationId" uuid,
    "LocationId" uuid,
    "BoxId" uuid,
    "Attributes" jsonb,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ItemLineages"
(
    "Id" uuid NOT NULL,
    "InventoryItemId" uuid NOT NULL,
    "Action" text COLLATE pg_catalog."default" NOT NULL,
    "TransactionId" uuid,
    "ChangedByUserId" text COLLATE pg_catalog."default" NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "StateSnapshot" jsonb,
    CONSTRAINT "PK_ItemLineages" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Listings"
(
    "Id" uuid NOT NULL,
    "InventoryItemId" uuid NOT NULL,
    "Price" numeric(18, 2) NOT NULL,
    "ReleaseDate" date NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Listings" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Listings_Price_Positive" CHECK ("Price" > 0)
);

CREATE TABLE IF NOT EXISTS public."Locations"
(
    "Id" uuid NOT NULL,
    "Name" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Coordinates" geometry(Point,4326),
    "OwnerId" text COLLATE pg_catalog."default" NOT NULL,
    "OrganizationId" uuid,
    "Metadata" jsonb,
    CONSTRAINT "PK_Locations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Manifests"
(
    "Id" uuid NOT NULL,
    "SourceLocationId" uuid NOT NULL,
    "DestinationLocationId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "OrganizationId" uuid,
    CONSTRAINT "PK_Manifests" PRIMARY KEY ("Id"),
    -- ManifestStatus enum: Draft = 0, Pending = 1, InTransit = 2, Received = 3, Cancelled = 4
    CONSTRAINT "CK_Manifests_Status_Range" CHECK ("Status" BETWEEN 0 AND 4)
);

CREATE TABLE IF NOT EXISTS public."NotificationPreferences"
(
    "Id" uuid NOT NULL,
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "EmailEnabled" boolean NOT NULL,
    "PushEnabled" boolean NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" uuid NOT NULL,
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "Title" text COLLATE pg_catalog."default" NOT NULL,
    "Message" text COLLATE pg_catalog."default" NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Offers"
(
    "Id" uuid NOT NULL,
    "ListingId" uuid NOT NULL,
    "BuyerId" text COLLATE pg_catalog."default" NOT NULL,
    "Amount" numeric(18, 2) NOT NULL,
    "Status" integer NOT NULL,
    "CounterAmount" numeric(18, 2),
    CONSTRAINT "PK_Offers" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Offers_Amount_Positive" CHECK ("Amount" > 0),
    CONSTRAINT "CK_Offers_CounterAmount_Positive" CHECK ("CounterAmount" IS NULL OR "CounterAmount" > 0),
    -- OfferStatus enum: Pending = 0, Accepted = 1, Rejected = 2, Countered = 3
    CONSTRAINT "CK_Offers_Status_Range" CHECK ("Status" BETWEEN 0 AND 3)
);

CREATE TABLE IF NOT EXISTS public."OrganizationMemberships"
(
    "OrganizationId" uuid NOT NULL,
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "Role" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_OrganizationMemberships" PRIMARY KEY ("OrganizationId", "UserId")
);

CREATE TABLE IF NOT EXISTS public."Organizations"
(
    "Id" uuid NOT NULL,
    "Name" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "LegalName" text COLLATE pg_catalog."default",
    "TaxId" text COLLATE pg_catalog."default",
    "Type" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Industry" text COLLATE pg_catalog."default",
    "DateCreated" timestamp with time zone NOT NULL,
    "DateDeleted" timestamp with time zone,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Organizations_Type" CHECK ("Type" IN ('Household', 'Business'))
);

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    "Id" uuid NOT NULL,
    "BuyerId" text COLLATE pg_catalog."default" NOT NULL,
    "SellerId" text COLLATE pg_catalog."default" NOT NULL,
    "Amount" numeric(18, 2) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "InventoryItemId" uuid NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Transactions_Amount_Positive" CHECK ("Amount" > 0)
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS public."__WorkerEFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___WorkerEFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Boxes"
    ADD CONSTRAINT "FK_Boxes_Locations_LocationId" FOREIGN KEY ("LocationId")
    REFERENCES public."Locations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Boxes_LocationId"
    ON public."Boxes"("LocationId");


ALTER TABLE IF EXISTS public."Boxes"
    ADD CONSTRAINT "FK_Boxes_Manifests_ManifestId" FOREIGN KEY ("ManifestId")
    REFERENCES public."Manifests" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "IX_Boxes_ManifestId"
    ON public."Boxes"("ManifestId");


ALTER TABLE IF EXISTS public."Boxes"
    ADD CONSTRAINT "FK_Boxes_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES public."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Boxes_OrganizationId"
    ON public."Boxes"("OrganizationId");


ALTER TABLE IF EXISTS public."ChatMessages"
    ADD CONSTRAINT "FK_ChatMessages_ChatThreads_ThreadId" FOREIGN KEY ("ThreadId")
    REFERENCES public."ChatThreads" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ChatMessages_ThreadId"
    ON public."ChatMessages"("ThreadId");


ALTER TABLE IF EXISTS public."InventoryItems"
    ADD CONSTRAINT "FK_InventoryItems_Boxes_BoxId" FOREIGN KEY ("BoxId")
    REFERENCES public."Boxes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_InventoryItems_BoxId"
    ON public."InventoryItems"("BoxId");


ALTER TABLE IF EXISTS public."InventoryItems"
    ADD CONSTRAINT "FK_InventoryItems_Categories_CategoryId" FOREIGN KEY ("CategoryId")
    REFERENCES public."Categories" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_InventoryItems_CategoryId"
    ON public."InventoryItems"("CategoryId");


ALTER TABLE IF EXISTS public."InventoryItems"
    ADD CONSTRAINT "FK_InventoryItems_Locations_LocationId" FOREIGN KEY ("LocationId")
    REFERENCES public."Locations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_InventoryItems_LocationId"
    ON public."InventoryItems"("LocationId");


ALTER TABLE IF EXISTS public."InventoryItems"
    ADD CONSTRAINT "FK_InventoryItems_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES public."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_InventoryItems_OrganizationId"
    ON public."InventoryItems"("OrganizationId");


ALTER TABLE IF EXISTS public."ItemLineages"
    ADD CONSTRAINT "FK_ItemLineages_InventoryItems_InventoryItemId" FOREIGN KEY ("InventoryItemId")
    REFERENCES public."InventoryItems" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ItemLineages_InventoryItemId"
    ON public."ItemLineages"("InventoryItemId");


ALTER TABLE IF EXISTS public."ItemLineages"
    ADD CONSTRAINT "FK_ItemLineages_Transactions_TransactionId" FOREIGN KEY ("TransactionId")
    REFERENCES public."Transactions" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_ItemLineages_TransactionId"
    ON public."ItemLineages"("TransactionId");


ALTER TABLE IF EXISTS public."Listings"
    ADD CONSTRAINT "FK_Listings_InventoryItems_InventoryItemId" FOREIGN KEY ("InventoryItemId")
    REFERENCES public."InventoryItems" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Listings_InventoryItemId"
    ON public."Listings"("InventoryItemId");


ALTER TABLE IF EXISTS public."Locations"
    ADD CONSTRAINT "FK_Locations_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES public."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Locations_OrganizationId"
    ON public."Locations"("OrganizationId");


ALTER TABLE IF EXISTS public."Manifests"
    ADD CONSTRAINT "FK_Manifests_Locations_DestinationLocationId" FOREIGN KEY ("DestinationLocationId")
    REFERENCES public."Locations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Manifests_DestinationLocationId"
    ON public."Manifests"("DestinationLocationId");


ALTER TABLE IF EXISTS public."Manifests"
    ADD CONSTRAINT "FK_Manifests_Locations_SourceLocationId" FOREIGN KEY ("SourceLocationId")
    REFERENCES public."Locations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Manifests_SourceLocationId"
    ON public."Manifests"("SourceLocationId");


ALTER TABLE IF EXISTS public."Manifests"
    ADD CONSTRAINT "FK_Manifests_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES public."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Manifests_OrganizationId"
    ON public."Manifests"("OrganizationId");


ALTER TABLE IF EXISTS public."Offers"
    ADD CONSTRAINT "FK_Offers_Listings_ListingId" FOREIGN KEY ("ListingId")
    REFERENCES public."Listings" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Offers_ListingId"
    ON public."Offers"("ListingId");


ALTER TABLE IF EXISTS public."OrganizationMemberships"
    ADD CONSTRAINT "FK_OrganizationMemberships_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES public."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "FK_Transactions_InventoryItems_InventoryItemId" FOREIGN KEY ("InventoryItemId")
    REFERENCES public."InventoryItems" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Transactions_InventoryItemId"
    ON public."Transactions"("InventoryItemId");


-- Added by migration AddSchemaHardeningConstraints (2026-07-12) — see docs/section-2-flagged-issues.md §2.13
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Categories_Name"
    ON public."Categories"("Name");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_NotificationPreferences_UserId"
    ON public."NotificationPreferences"("UserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Locations_OrganizationId_Name"
    ON public."Locations"("OrganizationId", "Name");

END;